org: typer
app: typer-importmap-deployer
service: typer-importmap-deployer

useDotenv: true
frameworkVersion: '3'

plugins:
  - serverless-s3-cleaner
custom:
  serverless-s3-cleaner:
    buckets:
      - typer-importmap-deployer-dev
provider:
  name: aws
  stage: dev
  region: 'us-east-1'
  runtime: nodejs14.x
  environment:
    REGION : us-east-1
    BUCKET_NAME: typer-importmap-deployer-dev
    NODE_ENV: dev
  iam:
    role:
      name: typer-importmap-deployer-role
      statements:
        - Effect: "Allow"
          Action:
            - "s3:Put*"
            - "s3:Get*"
            - "s3:List*"
            - "s3:Delete*"
          Resource:
            - arn:aws:s3:::typer-importmap-deployer-dev/*
            - arn:aws:s3:::typer-importmap-deployer-dev
        - Effect: "Allow"
          Action:
            - execute-api:Invoke
          Resource:
            - "arn:aws:execute-api:*:*:*"

functions:
  services:
    handler: handler.services
    events:
      - httpApi:
          path: /services
          method: "PATCH"

resources:
  Resources:
    ImportMapBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: "PublicRead"
        BucketName: typer-importmap-deployer-dev
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
              AllowedOrigins:
                - "*"
              