service: typer-importmap-deployer

useDotenv: true

frameworkVersion: '3'

plugins:
  - serverless-s3-cleaner

custom:
  serverless-s3-cleaner:
    buckets:
      - typer-importmap-deployer-${opt:stage,self:provider.stage}

provider:
  name: aws
  stage: dev
  region: 'us-east-1'
  runtime: nodejs14.x
  environment:
    REGION: us-east-1
    BUCKET_NAME: typer-importmap-deployer-${opt:stage,self:provider.stage}
    NODE_ENV: ${opt:stage,self:provider.stage}
  iam:
    role:
      name: typer-importmap-deployer-${opt:stage,self:provider.stage}-role
      statements:
        - Effect: "Allow"
          Action:
            - "s3:Put*"
            - "s3:Get*"
            - "s3:List*"
            - "s3:Delete*"
            - "s3:GetBucketPolicy"
            - "s3:PutBucketPolicy"
          Resource:
            - arn:aws:s3:::typer-importmap-deployer-${opt:stage,self:provider.stage}/*
            - arn:aws:s3:::typer-importmap-deployer-${opt:stage,self:provider.stage}
        - Effect: "Allow"
          Action:
            - execute-api:Invoke
          Resource:
            - "arn:aws:execute-api:*:*:*"

functions:
  services:
    handler: handler.services
    events:
      - httpApi:
          path: /services
          method: "PATCH"
          authorizer:
            type: aws_iam

resources:
  Resources:
    ImportMapBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: typer-importmap-deployer-${opt:stage,self:provider.stage}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
              AllowedOrigins:
                - "*"
    ImportMapBucketPolicy:
      Type: AWS::S3::BucketPolicy
      DependsOn: ImportMapBucket
      Properties:
        Bucket: typer-importmap-deployer-${opt:stage,self:provider.stage}
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action: s3:GetObject
              Resource: "arn:aws:s3:::typer-importmap-deployer-${opt:stage,self:provider.stage}/*"