org: typer
app: typer-importmap-deployer
service: typer-importmap-deployer

frameworkVersion: '3'

plugins:
  - serverless-s3-cleaner
custom:
  serverless-s3-cleaner:
    buckets:
      - ${self:service}-${opt:stage,self:provider.stage}
provider:
  name: aws
  stage: dev
  region: 'us-east-1'
  runtime: nodejs14.x
  environment:
    REGION : ${opt:region,self:provider.region}
    BUCKET_NAME: ${self:service}-${opt:stage,self:provider.stage}
    NODE_ENV: ${opt:stage,self:provider.stage}
  iam:
    role:
      name: ${self:service}-${opt:stage,self:provider.stage}-${opt:region,self:provider.region}-role
      statements:
        - Effect: "Allow"
          Action:
            - "s3:Put*"
            - "s3:Get*"
            - "s3:List*"
            - "s3:Delete*"
          Resource:
            - arn:aws:s3:::${self:service}-${opt:stage,self:provider.stage}/*
            - arn:aws:s3:::${self:service}-${opt:stage,self:provider.stage}
        - Effect: "Allow"
          Action:
            - execute-api:Invoke
          Resource:
            - "arn:aws:execute-api:*:*:*"

functions:
  services:
    handler: handler.services
    events:
      - httpApi:
          path: /services
          method: "PATCH"

resources:
  Resources:
    ImportMapBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: "PublicRead"
        BucketName:  ${self:service}-${opt:stage,self:provider.stage}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
              AllowedOrigins:
                - "*"
              