ervice: typer-importmap-deployer-development

useDotenv: true

frameworkVersion: '3'

plugins:
  - serverless-s3-cleaner
  - serverless-dotenv-plugin

custom:
  serverless-s3-cleaner:
    buckets:
      - typer-importmap-deployer-development
  dotenv:
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - NODE_ENV
    required:
      env:
        - REGION
      file: true

provider:
  name: aws
  stage: development
  region: ${env:REGION}
  runtime: nodejs14.x
  httpApi:
    name: typer-importmap-deployer-development
  environment:
    STAGE: development
    BUCKET_NAME: typer-importmap-deployer-development
  iam:
    role:
      name: typer-importmap-deployer-role-development
      statements:
        - Effect: "Allow"
          Action:
            - "s3:Put*"
            - "s3:Get*"
            - "s3:List*"
            - "s3:Delete*"
            - "s3:GetBucketPolicy"
            - "s3:PutBucketPolicy"
          Resource:
            - arn:aws:s3:::typer-importmap-deployer-development/*
            - arn:aws:s3:::typer-importmap-deployer-development
        - Effect: "Allow"
          Action:
            - execute-api:Invoke
          Resource:
            - "arn:aws:execute-api:*:*:*"

functions:
  services:
    handler: handler.services
    events:
      - httpApi:
          path: /services
          method: "PATCH"
          authorizer:
            type: aws_iam

resources:
  Resources:
    ImportMapBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: typer-importmap-deployer-development
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
              AllowedOrigins:
                - "*"
    ImportMapBucketPolicy:
      Type: AWS::S3::BucketPolicy
      DependsOn: ImportMapBucket
      Properties:
        Bucket: typer-importmap-deployer-development
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action: s3:GetObject
              Resource: "arn:aws:s3:::typer-importmap-deployer-development/*"