name: Deploy to development

on:
  push:
    branches:
      - development

env:
  REGION: ${{ secrets.REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: development
    steps:
    - uses: actions/checkout@v3
    - name: "Install Node"
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: "Install dependencies"
      run: yarn install --frozen-lockfile
    - name: "Create .env.development file"
      run: |
        echo "REGION=${REGION}" > .env.development
        echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> .env.development
        echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> .env.development
    - name: "Run serverless deploy"
      run: yarn sls:deploy:development